# Generated by Django 4.1.5 on 2023-01-15 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_contributor"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contributor",
            unique_together={("project_id", "user_id")},
        ),
    ]
