# Generated by Django 4.1.5 on 2023-01-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_contributor_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributor",
            name="permission",
            field=models.CharField(
                choices=[("CTR", "Contributor"), ("OWN", "Owner")],
                default="CTR",
                max_length=255,
            ),
        ),
    ]
