# Generated by Django 4.1.5 on 2023-01-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="type",
            field=models.CharField(
                choices=[
                    ("back", "Back-end"),
                    ("front", "Front-end"),
                    ("iOS", "iOS"),
                    ("Android", "Android"),
                ],
                max_length=255,
            ),
        ),
    ]
