# Generated by Django 4.1.5 on 2023-01-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_project_description_alter_project_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="priority",
            field=models.CharField(
                choices=[("low", "Faible"), ("medium", "Moyenne"), ("high", "Haute")],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "A faire"),
                    ("in progress", "En cours"),
                    ("finished", "Terminé"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="tag",
            field=models.CharField(
                choices=[
                    ("bug", "Bug"),
                    ("improvement", "Amélioration"),
                    ("task", "Tâche"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="type",
            field=models.CharField(
                choices=[
                    ("back", "Back-end"),
                    ("front", "Front-end"),
                    ("iOS", "iOS"),
                    ("android", "Android"),
                ],
                max_length=255,
            ),
        ),
    ]
